In [1]:
import tensorflow as tf

c = tf.constant([[[[1, 2]]]], tf.float32)
print(c)
s1 = tf.ones([1,1,1,1], tf.float32)*10
s2 = tf.ones([1,1,1,1], tf.float32)*20
shared = [c, s1, s2]

2022-07-11 17:02:00.352892: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-11 17:02:00.365546: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-11 17:02:00.365842: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


tf.Tensor([[[[1. 2.]]]], shape=(1, 1, 1, 2), dtype=float32)


2022-07-11 17:02:00.367286: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-11 17:02:00.368007: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-11 17:02:00.368198: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-11 17:02:00.368331: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA 

In [4]:
def shared_concatenation(sides, num_classes):
    shared_concat = []
    for j in range(len(sides)):
        if sides[j].shape[-1] == num_classes:
            shared_concat.append(sides[j])
        else:
            shared_concat.append(tf.repeat(sides[j], num_classes, axis=-1))
    return tf.keras.layers.Concatenate(axis=-1)(shared_concat)

def fused_classification(x, num_classes, name=None):
    shape = tf.cast(tf.shape(x),x.dtype)
    x = tf.keras.layers.Reshape((1,1,-1,2))(x)
    x = tf.transpose(x, perm=[0, 1, 2, 4, 3])
    print(x)
    x = tf.keras.layers.Conv2D(filters=2, kernel_size=3, stride(),name=name)(x)
    print(x)
    return tf.squeeze(x,axis=-1)

In [5]:
s = shared_concatenation(shared,2)
print(s)
g = fused_classification(s, 2)
print(g)

tf.Tensor([[[[ 1.  2. 10. 10. 20. 20.]]]], shape=(1, 1, 1, 6), dtype=float32)
tf.Tensor(
[[[[[ 1. 10. 20.]
    [ 2. 10. 20.]]]]], shape=(1, 1, 1, 2, 3), dtype=float32)
tf.Tensor(
[[[[[16.688965]
    [17.503906]]]]], shape=(1, 1, 1, 2, 1), dtype=float32)
tf.Tensor([[[[16.688965 17.503906]]]], shape=(1, 1, 1, 2), dtype=float32)
